# Generated by Django 5.1.2 on 2024-10-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="join_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
